### ISSUE TITLE
Store Avatars Locally

### ISSUE THREAD

**Issue by adampickering** [Astoundify/wp-simple-social-login#43]
<img width="826" alt="screen shot 2018-08-09 at 1 35 24 pm" src="https://user-images.githubusercontent.com/746776/43916083-941f4718-9bda-11e8-9e7e-cfef29b4bb43.png">
<img width="208" alt="screen shot 2018-08-09 at 1 35 09 pm" src="https://user-images.githubusercontent.com/746776/43916084-942df65a-9bda-11e8-9bea-283c92ea6edb.png">

**Comment by adampickering** [comment]
Google seems to pull the image fine.

**Comment by spencerfinnell** [comment]
It uses the email for that account for a Gravatar. The previous version didn't store an avatar locally. Not sure what other plugins do -- I'll look.
